//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codecrete.SwissQRBill.Generator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QRBillText_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QRBillText_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codecrete.SwissQRBill.Generator.Resources.QRBillText-de", typeof(QRBillText_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annahmestelle.
        /// </summary>
        internal static string AcceptancePoint {
            get {
                return ResourceManager.GetString("AcceptancePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto / Zahlbar an.
        /// </summary>
        internal static string AccountPayableTo {
            get {
                return ResourceManager.GetString("AccountPayableTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusätzliche Informationen.
        /// </summary>
        internal static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrag.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Währung.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlbar durch.
        /// </summary>
        internal static string PayableBy {
            get {
                return ResourceManager.GetString("PayableBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlbar durch (Name/Adresse).
        /// </summary>
        internal static string PayableByNameAddr {
            get {
                return ResourceManager.GetString("PayableByNameAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlteil.
        /// </summary>
        internal static string PaymentPart {
            get {
                return ResourceManager.GetString("PaymentPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empfangsschein.
        /// </summary>
        internal static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenz.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
    }
}
